name: Run tests

on: push

jobs:
  tests:
    name: Run Xcode Tests
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: ["14.2.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-iOS_derived_data-xcode_${{ matrix.xcode }}
          restore-keys: |
            ${{ runner.os }}-iOS_derived_data

      - name: Build & Test
        run: |
          file_to_build="`ls -A | grep -i \\.xcodeproj\$`"
          xcodebuild -project "$file_to_build" -scheme Zotero -destination "platform=iOS Simulator,name=iPhone 14" test | xcpretty --color