name: Run tests

on: 
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:

jobs:
  tests:
    name: Run Xcode Tests
    runs-on: macos-26
    strategy:
      matrix:
        xcode: ["26.2"]
        ios_version: ["26.2"]
        device_name: ["iPhone 17"]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install SwiftGen
        run: which swiftgen || HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install swiftgen

      - name: Install SwiftLint
        run: which swiftlint || HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install swiftlint

      - name: Install NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash

      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Clean & Build & Test
        uses: sersoft-gmbh/xcodebuild-action@v4.0
        with:
          project: Zotero.xcodeproj
          scheme: Zotero
          destination: platform=iOS Simulator,OS=${{ matrix.ios_version }},name=${{ matrix.device_name }}
          action: clean test