name: Run tests

on: 
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:

jobs:
  tests:
    name: Run Xcode Tests
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ["14.3.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install SwiftGen
        run: which swiftgen || HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install swiftgen

      - name: Install SwiftLint
        run: which swiftlint || HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install swiftlint

      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-iOS_derived_data-xcode_${{ matrix.xcode }}
          restore-keys: |
            ${{ runner.os }}-iOS_derived_data

      - name: Build & Test
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: Zotero.xcodeproj
          scheme: Zotero
          destination: platform=iOS Simulator,name=iPhone 14
          action: test